### ISSUE TITLE
Unable to run image from ACR on virtual node

### ISSUE THREAD

**Issue by solomson** [Azure-Samples/virtual-node-autoscale#38]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Working AKS cluster with virtual nodes enabled
Helm and tiller installed to cluster
Service principal with acr pull role assigned
Linux based docker images in ACR repo
Created docker-registry secret in cluster

### Any log messages given by the failure
>
None
### Expected/desired behavior
>
Expect Pods from private images to run on virtual node

### OS and Version?
Windows 7 & 10
### Versions
>
Latest
Kubernetes version 1.12.6
### Mention any other details that might be useful

Issue is similar to: https://github.com/virtual-kubelet/virtual-kubelet/issues/505
I hope to provide more details to get a fix going

In order to schedule onto the virtual node I had to add the following code to the values.yaml file :
```
  nodeSelector:
  kubernetes.io/role: agent
  beta.kubernetes.io/os: linux
  type: virtual-kubelet

  affinity: {}

  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
  - key: azure.com/aci
  effect: NoSchedule
```
I took this from the yaml file in https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli
I also added 
```
          imagePullSecrets:
          - name: acr-auth 
```
 under the specified container to the app-deployment.yaml file 

Using the above nodeSelector and tolerations additions to the base values.yaml file made the default image (virtualnode/samples/online-store) run and scale perfectly in ACI. When I then change the image path to my own private ACR image, the pod recieves a state "ProviderFailed" a few seconds after creation. Haven't found any clues from kubectl get events, and logs from pods are not working as the "resource containergroup____ doesn't exist" in my resource group in Azure.

If the above code was not added, the pod would schedule onto my VM in the aks cluster. I did not do the optional part described in readme.md "Install Virtual Node admission-controller".
Without adding nodeselector and tolerations I managed to run instances of my private ACR images on the VM node. However I want these pods to run and autoscale in ACI via virtual node, not on the VM node.

I believe that the above shows that the issue is specific to running private container images on virtual nodes as the private images run fine on my VM node.

Full code of values.yaml:
```
lf:
  image:
    repository: mcr.microsoft.com/virtualnode/samples/live-metrics-forwarder
    tag: latest
    pullPolicy: IfNotPresent
  service:
      type: ClusterIP
      port: 55678
  resources:
    requests:
      cpu: 500m
      memory: 0.1G
app:
  throttle:
    sleep: 1
    limit: 1000

  replicaCount: 1
  image:
    repository: <redacted>.azurecr.io/<redacted2>/<redacted3>
    tag: latest
    pullPolicy: Always
    imagePullSecrets:
    - name: acr-auth
  
  service:
    type: ClusterIP
    port: 80
  
  ingress:
    enabled: true
    host: store.<redacted>.nip.io
    annotations:
      kubernetes.io/ingress.class: addon-http-application-routing

  resources:
    requests:
      cpu: 500m
      memory: 0.6G

  nodeSelector:
  kubernetes.io/role: agent
  beta.kubernetes.io/os: linux
  type: virtual-kubelet

  affinity: {}

  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
  - key: azure.com/aci
  effect: NoSchedule_

promMonitor: online-store

counter:
  replicaCount: 1
  # The interval in seconds
  interval: 5
  specialNodeName: virtual-node-aci-linux
  image:
    repository: mcr.microsoft.com/virtualnode/samples/container-counter
    tag: latest 
    pullPolicy: IfNotPresent

hpa:
  metricTarget: 2
  minReplicas: 1 
  maxReplicas: 4

appInsight:
  enabled: false
  key:
```
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.
